apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "banksvc"
    version: "1.0.0"
  name: "banksvc"
spec:
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
      name: "http"
  selector:
    app: "banksvc"
    version: "1.0.0"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    version: "1.0.0"
    app: "banksvc"
  name: "banksvc"
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1.0.0"
      app: "banksvc"
  template:
    metadata:
      labels:
        version: "1.0.0"
        app: "banksvc"
    spec:
      containers:
        - image: "knightbeat/banksvc:1.0.1"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 5
            tcpSocket:
              port: 8080
          name: "products-deployment"
          ports:
            - containerPort: 8080
              protocol: "TCP"
